"""Add unique constraint to memberships

Revision ID: 4347b727b544
Revises: 91a2a1e77256
Create Date: 2025-12-31 01:31:22.640074

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4347b727b544"
down_revision: Union[str, Sequence[str], None] = "91a2a1e77256"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_membership_user_workspace", "memberships", ["user_id", "workspace_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_membership_user_workspace", "memberships", type_="unique")
    # ### end Alembic commands ###
