"""Add daily_request_limit column to workspaces table

Revision ID: 806cf84404f3
Revises: 716ab90ef94b
Create Date: 2025-10-21 17:13:02.119358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '806cf84404f3'
down_revision: Union[str, Sequence[str], None] = '716ab90ef94b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add daily_request_limit with default value of 10 for existing rows
    op.add_column('workspaces', sa.Column('daily_request_limit', sa.Integer(), nullable=False, server_default='10'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'daily_request_limit')
    # ### end Alembic commands ###
