"""Add daily_request_limit column to workspaces table

Revision ID: 806cf84404f3
Revises: 716ab90ef94b
Create Date: 2025-10-21 17:13:02.119358

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "806cf84404f3"
down_revision: Union[str, Sequence[str], None] = "716ab90ef94b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema, Add daily_request_limit column with default value of 10 for existing rows"""
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # check if the column already exists in database
    columns = [c["name"] for c in inspector.get_columns("workspaces")]

    if "daily_request_limit" not in columns:
        op.add_column(
            "workspaces",
            sa.Column(
                "daily_request_limit", sa.Integer(), nullable=False, server_default="10"
            ),
        )
        
        ''' in SQL, it basically means'''
        #ALTER TABLE workspaces
        #ADD COLUMN daily_request_limit INTEGER NOT NULL DEFAULT 10;
        
    else:
        print("  ⊘ Column 'workspaces.daily_request_limit' already exists, skipping...")

    # Add daily_request_limit with default value of 10 for existing rows

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspaces", "daily_request_limit")
    # ### end Alembic commands ###
