"""Add security events table

Revision ID: 80ff9d48ddc5
Revises: f1a2b3c4d5e6
Create Date: 2025-12-11 07:15:58.954873

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy import inspect
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "80ff9d48ddc5"
down_revision: Union[str, Sequence[str], None] = "f1a2b3c4d5e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def table_exists(table_name: str) -> bool:
    """Check if a table exists in the database."""
    bind = op.get_bind()
    inspector = inspect(bind)
    return table_name in inspector.get_table_names()


def index_exists(index_name: str, table_name: str) -> bool:
    """Check if an index exists on a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    indexes = inspector.get_indexes(table_name)
    return any(idx["name"] == index_name for idx in indexes)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create table if it doesn't exist
    if not table_exists("security_events"):
        op.create_table(
            "security_events",
            sa.Column("id", sa.String(), nullable=False),
            sa.Column(
                "event_type",
                sa.Enum("PROMPT_INJECTION", "GUARD_DEGRADED", name="securityeventtype"),
                nullable=False,
            ),
            sa.Column("severity", sa.String(), nullable=False),
            sa.Column("workspace_id", sa.String(), nullable=True),
            sa.Column("slack_integration_id", sa.String(), nullable=True),
            sa.Column("slack_user_id", sa.String(), nullable=True),
            sa.Column("message_preview", sa.Text(), nullable=True),
            sa.Column("guard_response", sa.String(), nullable=True),
            sa.Column("reason", sa.String(), nullable=True),
            sa.Column(
                "event_metadata", postgresql.JSON(astext_type=sa.Text()), nullable=True
            ),
            sa.Column(
                "detected_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=True,
            ),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=True,
            ),
            sa.ForeignKeyConstraint(
                ["slack_integration_id"],
                ["slack_installations.id"],
            ),
            sa.ForeignKeyConstraint(
                ["workspace_id"],
                ["workspaces.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )

    # Create each index if it doesn't exist
    if not index_exists("idx_security_events_detected_at", "security_events"):
        op.create_index(
            "idx_security_events_detected_at",
            "security_events",
            ["detected_at"],
            unique=False,
        )

    if not index_exists("idx_security_events_slack_integration", "security_events"):
        op.create_index(
            "idx_security_events_slack_integration",
            "security_events",
            ["slack_integration_id"],
            unique=False,
        )

    if not index_exists("idx_security_events_slack_user", "security_events"):
        op.create_index(
            "idx_security_events_slack_user",
            "security_events",
            ["slack_user_id"],
            unique=False,
        )

    if not index_exists("idx_security_events_type", "security_events"):
        op.create_index(
            "idx_security_events_type", "security_events", ["event_type"], unique=False
        )

    if not index_exists("idx_security_events_workspace", "security_events"):
        op.create_index(
            "idx_security_events_workspace",
            "security_events",
            ["workspace_id"],
            unique=False,
        )

    # Drop the newrelic index if it exists (cleanup from previous migration)
    if index_exists("idx_newrelic_integration_workspace", "newrelic_integrations"):
        op.drop_index(
            op.f("idx_newrelic_integration_workspace"),
            table_name="newrelic_integrations",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("idx_newrelic_integration_workspace"),
        "newrelic_integrations",
        ["workspace_id"],
        unique=False,
    )
    op.drop_index("idx_security_events_workspace", table_name="security_events")
    op.drop_index("idx_security_events_type", table_name="security_events")
    op.drop_index("idx_security_events_slack_user", table_name="security_events")
    op.drop_index("idx_security_events_slack_integration", table_name="security_events")
    op.drop_index("idx_security_events_detected_at", table_name="security_events")
    op.drop_table("security_events")
    # ### end Alembic commands ###
