"""add_service_health_review_tables

Revision ID: 9055f8216e50
Revises: z000_baseline_snapshot
Create Date: 2026-02-03 12:11:12.182880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9055f8216e50'
down_revision: Union[str, Sequence[str], None] = 'z000_baseline_snapshot'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('review_week_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('review_week_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'GENERATING', 'COMPLETED', 'FAILED', name='reviewstatus'), nullable=False),
    sa.Column('triggered_by', sa.Enum('SCHEDULER', 'MANUAL', 'API', name='reviewtriggeredby'), nullable=False),
    sa.Column('overall_health_score', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('analyzed_commit_sha', sa.String(length=40), nullable=True),
    sa.Column('codebase_changed', sa.Boolean(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generation_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_count_analyzed', sa.Integer(), nullable=True),
    sa.Column('log_volume_analyzed', sa.Integer(), nullable=True),
    sa.Column('metric_count_analyzed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_service_reviews_created_at', 'service_reviews', ['created_at'], unique=False)
    op.create_index('idx_service_reviews_service', 'service_reviews', ['service_id'], unique=False)
    op.create_index('idx_service_reviews_service_week', 'service_reviews', ['service_id', 'review_week_start'], unique=True)
    op.create_index('idx_service_reviews_status', 'service_reviews', ['status'], unique=False)
    op.create_index('idx_service_reviews_week_start', 'service_reviews', ['review_week_start'], unique=False)
    op.create_index('idx_service_reviews_workspace', 'service_reviews', ['workspace_id'], unique=False)
    op.create_table('review_errors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('error_type', sa.String(length=255), nullable=False),
    sa.Column('error_message_sample', sa.Text(), nullable=True),
    sa.Column('error_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('affected_endpoints', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('stack_trace_sample', sa.Text(), nullable=True),
    sa.Column('investigation_status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='investigationstatus'), nullable=False),
    sa.Column('investigation_job_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['investigation_job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['service_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_errors_fingerprint', 'review_errors', ['error_fingerprint'], unique=False)
    op.create_index('idx_review_errors_occurrence', 'review_errors', ['occurrence_count'], unique=False)
    op.create_index('idx_review_errors_review', 'review_errors', ['review_id'], unique=False)
    op.create_table('review_logging_gaps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('gap_description', sa.Text(), nullable=False),
    sa.Column('gap_category', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='gappriority'), nullable=False),
    sa.Column('affected_files', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('affected_functions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('suggested_log_locations', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('suggested_log_statement', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('pr_status', sa.Enum('NOT_CREATED', 'PENDING', 'CREATED', 'MERGED', 'CLOSED', name='prstatus'), nullable=False),
    sa.Column('pr_url', sa.String(length=500), nullable=True),
    sa.Column('pr_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pr_branch_name', sa.String(length=255), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['service_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_logging_gaps_acknowledged', 'review_logging_gaps', ['acknowledged'], unique=False)
    op.create_index('idx_review_logging_gaps_priority', 'review_logging_gaps', ['priority'], unique=False)
    op.create_index('idx_review_logging_gaps_review', 'review_logging_gaps', ['review_id'], unique=False)
    op.create_table('review_metrics_gaps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('gap_description', sa.Text(), nullable=False),
    sa.Column('gap_category', sa.String(length=100), nullable=True),
    sa.Column('metric_type', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='gappriority'), nullable=False),
    sa.Column('affected_components', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('suggested_metric_names', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('implementation_guide', sa.Text(), nullable=True),
    sa.Column('example_code', sa.Text(), nullable=True),
    sa.Column('integration_provider', sa.String(length=50), nullable=True),
    sa.Column('dashboard_link', sa.String(length=500), nullable=True),
    sa.Column('pr_status', sa.Enum('NOT_CREATED', 'PENDING', 'CREATED', 'MERGED', 'CLOSED', name='prstatus'), nullable=False),
    sa.Column('pr_url', sa.String(length=500), nullable=True),
    sa.Column('pr_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pr_branch_name', sa.String(length=255), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['service_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_metrics_gaps_acknowledged', 'review_metrics_gaps', ['acknowledged'], unique=False)
    op.create_index('idx_review_metrics_gaps_priority', 'review_metrics_gaps', ['priority'], unique=False)
    op.create_index('idx_review_metrics_gaps_review', 'review_metrics_gaps', ['review_id'], unique=False)
    op.create_table('review_schedules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('generation_day_of_week', sa.Integer(), nullable=False),
    sa.Column('generation_hour_utc', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('last_review_id', sa.String(), nullable=True),
    sa.Column('last_review_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_review_status', sa.String(length=50), nullable=True),
    sa.Column('next_scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['last_review_id'], ['service_reviews.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id')
    )
    op.create_index('idx_review_schedules_enabled', 'review_schedules', ['enabled'], unique=False)
    op.create_index('idx_review_schedules_enabled_next', 'review_schedules', ['enabled', 'next_scheduled_at'], unique=False)
    op.create_index('idx_review_schedules_next_scheduled', 'review_schedules', ['next_scheduled_at'], unique=False)
    op.create_index('idx_review_schedules_service', 'review_schedules', ['service_id'], unique=False)
    op.create_index('idx_review_schedules_workspace', 'review_schedules', ['workspace_id'], unique=False)
    op.create_table('review_slis',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('sli_name', sa.String(length=100), nullable=False),
    sa.Column('sli_category', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('previous_week_score', sa.Integer(), nullable=True),
    sa.Column('score_trend', sa.Enum('UP', 'DOWN', 'STABLE', name='scoretrend'), nullable=True),
    sa.Column('target_value', sa.String(length=50), nullable=True),
    sa.Column('actual_value', sa.String(length=50), nullable=True),
    sa.Column('measurement_unit', sa.String(length=50), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('query_used', sa.Text(), nullable=True),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('contributing_factors', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['service_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_slis_category', 'review_slis', ['sli_category'], unique=False)
    op.create_index('idx_review_slis_name', 'review_slis', ['sli_name'], unique=False)
    op.create_index('idx_review_slis_review', 'review_slis', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_review_slis_review', table_name='review_slis')
    op.drop_index('idx_review_slis_name', table_name='review_slis')
    op.drop_index('idx_review_slis_category', table_name='review_slis')
    op.drop_table('review_slis')
    op.drop_index('idx_review_schedules_workspace', table_name='review_schedules')
    op.drop_index('idx_review_schedules_service', table_name='review_schedules')
    op.drop_index('idx_review_schedules_next_scheduled', table_name='review_schedules')
    op.drop_index('idx_review_schedules_enabled_next', table_name='review_schedules')
    op.drop_index('idx_review_schedules_enabled', table_name='review_schedules')
    op.drop_table('review_schedules')
    op.drop_index('idx_review_metrics_gaps_review', table_name='review_metrics_gaps')
    op.drop_index('idx_review_metrics_gaps_priority', table_name='review_metrics_gaps')
    op.drop_index('idx_review_metrics_gaps_acknowledged', table_name='review_metrics_gaps')
    op.drop_table('review_metrics_gaps')
    op.drop_index('idx_review_logging_gaps_review', table_name='review_logging_gaps')
    op.drop_index('idx_review_logging_gaps_priority', table_name='review_logging_gaps')
    op.drop_index('idx_review_logging_gaps_acknowledged', table_name='review_logging_gaps')
    op.drop_table('review_logging_gaps')
    op.drop_index('idx_review_errors_review', table_name='review_errors')
    op.drop_index('idx_review_errors_occurrence', table_name='review_errors')
    op.drop_index('idx_review_errors_fingerprint', table_name='review_errors')
    op.drop_table('review_errors')
    op.drop_index('idx_service_reviews_workspace', table_name='service_reviews')
    op.drop_index('idx_service_reviews_week_start', table_name='service_reviews')
    op.drop_index('idx_service_reviews_status', table_name='service_reviews')
    op.drop_index('idx_service_reviews_service_week', table_name='service_reviews')
    op.drop_index('idx_service_reviews_service', table_name='service_reviews')
    op.drop_index('idx_service_reviews_created_at', table_name='service_reviews')
    op.drop_table('service_reviews')
    # ### end Alembic commands ###
