"""Add newsletter_subscribed to users

Revision ID: c1dd6edf73ca
Revises: f1x3num5
Create Date: 2025-12-29 18:15:21.103651

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c1dd6edf73ca"
down_revision: Union[str, Sequence[str], None] = "f1x3num5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column with server_default to handle existing rows
    op.add_column(
        "users",
        sa.Column(
            "newsletter_subscribed",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "newsletter_subscribed")
    # ### end Alembic commands ###
