"""Add mailgun_emails table

Revision ID: iqx5rixmd6xw
Revises: 806cf84404f3
Create Date: 2025-10-23 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "iqx5rixmd6xw"
down_revision: Union[str, Sequence[str], None] = "806cf84404f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create mailgun_emails table
    op.create_table(
        "mailgun_emails",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "sent_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("subject", sa.String(), nullable=True),
        sa.Column("message_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    # Create indexes
    op.create_index(
        "idx_mailgun_emails_user", "mailgun_emails", ["user_id"], unique=False
    )
    op.create_index(
        "idx_mailgun_emails_sent_at", "mailgun_emails", ["sent_at"], unique=False
    )
    op.create_index(
        "idx_mailgun_emails_status", "mailgun_emails", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes first
    op.drop_index("idx_mailgun_emails_status", table_name="mailgun_emails")
    op.drop_index("idx_mailgun_emails_sent_at", table_name="mailgun_emails")
    op.drop_index("idx_mailgun_emails_user", table_name="mailgun_emails")

    # Drop table
    op.drop_table("mailgun_emails")
    # ### end Alembic commands ###
